### ISSUE TITLE
Backend Locations API

### ISSUE THREAD

**Issue by remkop22** [remopas/skate-map#4]
### Tasks
- [x] Define Location Model
- [x] Set up database and backend database connection
- [x] Create endpoints
- [x] Create filtering logic

### Endpoints
- [x] GET `/locations?q=<query>&sort=distance&filter=has:half pipe`
- [x] GET `/locations/tags`
- [x] GET `/locations/objects` 
- [ ] GET `/locations/<location_id>/`
